import type { NextPage } from "next";
import Head from "next/head";
import TodoContainer from "../containers/TodoContainer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <h1 className="font-body text-h3 pl-11">TODO List</h1>
      <TodoContainer />
    </div>
  );
};

export default Home;
